version: '3.1'
services:
    webserver:
        image: apache_php_https
        restart: always
        volumes:
            - ./html:/var/www/html
            -  ${APACHE_LOG_VOLUME}:/var/log/apache2
            - ${APACHE_CONF}:/etc/apache2/sites-available/000-default.conf
            - ${SSL_VOLUME}:/var/imported/ssl
        ports:
            - "${HOST_HTTP_PORT}:80"
            - "${HOST_HTTPS_PORT}:443"
