version: '3.1'
services:
    webserver_a:
        image: apache_php_https
        restart: always
        volumes:
            - ./html:/var/www/html
            - ./apache_log:/var/log/apache2
            - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./ssl_a:/var/imported/ssl
        ports:
            - "80:80"
            - "443:443"
    webserver_b:
        image: apache_php_https
        restart: always
        volumes:
            - ./html:/var/www/html
            - ./apache_log:/var/log/apache2
            - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./ssl_b:/var/imported/ssl
        ports:
            - "8080:80"
            - "8443:443"            
